services:
  public-api:
    env_file: .env
    build:
      context: .
      dockerfile: public-api/Dockerfile
    ports:
      - "3001:3001"
    networks: [microservices-net]

  user-service:
    platform: linux/amd64
    env_file: .env
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "3002:3002"
    networks: [microservices-net]

  item-service:
    platform: linux/amd64
    env_file: .env
    build:
      context: .
      dockerfile: item-service/Dockerfile
    ports:
      - "3003:3003"
    networks: [ microservices-net ]

  api-gateway:
    env_file: .env
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - public-api
      - user-service
    networks: [microservices-net]

networks:
  microservices-net:
    driver: bridge